config/routes.rb
IMSRails3::Application.routes.draw do
  
  resources :users do
    collection  do
      post 'verify_login'
      get 'search'
    end
  end

  resources :interviews do
    collection do
      get 'csv_upload'
      post 'import_csv'      
      get 'search'
    end    
  end
  match 'interview/:id/download_attachment/:attachment_id' => "interviews#download_attachment",:as=>"download_attachment"
  match 'interview/upload_personal_doc/:id' => "interviews#upload_personal_doc",:as=>"upload_personal_doc"

  match 'interview/import_personal_doc/:id' => "interviews#import_personal_doc",:as=>"import_personal_doc"
  match 'interview/index' => "interviews#get_content_to_display",:as=>"get_content_to_display"

  match 'logout' => "users#logout",:as=>"logout"
  root :to => "users#login"
  

end

app/controllers/interviews_controller.rb
require 'iconv'
class InterviewsController < ApplicationController
  before_filter :authenticate
  # GET /interviews
  # GET /interviews.xml
  def index
    params[:page] ||=1    
    @interviews = Interview.paginate(:per_page=>9,:page=>params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interviews }
      format.csv {  generate_csv_headers("Interview-#{Time.now.strftime("%Y%m%d")}") }
    end
  end

  # GET /interviews/1
  # GET /interviews/1.xml
  def show
    @interview = Interview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interview }
    end
  end

  # GET /interviews/new
  # GET /interviews/new.xml
  def new
    @interview = Interview.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interview }
    end
  end

  # GET /interviews/1/edit
  def edit
    @interview = Interview.find(params[:id])
  end

  # POST /interviews
  # POST /interviews.xml
  def create
    @interview = Interview.new(params[:interview])

    respond_to do |format|
      if @interview.save
        format.html { redirect_to(@interview, :notice => 'Interview was successfully created.') }
        format.xml  { render :xml => @interview, :status => :created, :location => @interview }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviews/1
  # PUT /interviews/1.xml
  def update
    @interview = Interview.find(params[:id])

    respond_to do |format|
      if @interview.update_attributes(params[:interview])
        format.html { redirect_to(@interview, :notice => 'Interview was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.xml
  def destroy
    @interview = Interview.find(params[:id])
    @interview.destroy

    respond_to do |format|
      format.html { redirect_to(interviews_url) }
      format.xml  { head :ok }
    end
  end

  def csv_upload
    
  end
  
  def import_csv
    #   begin
    file = params[:csv_import][:file]
    logcount=0
    Interview.transaction do
      FasterCSV.parse(file.tempfile, :headers => true) do |row|
        Interview.create!(row.to_hash)
        logcount += 1
      end
    end
    flash[:notice] = "Successfully added #{logcount} Participant(s)."
    redirect_to interviews_path
    #    rescue => exception
    #      # If an exception is thrown, the transaction rolls back and we end up in this rescue block
    #      error = ERB::Util.h(exception.to_s) # get the error and HTML escape it
    #      flash[:error] = "Error adding logs.  (#{error}).  Please try again."
    #      redirect_to csv_upload_interviews_url
    #   end
  end

  def upload_personal_doc
    @interview = Interview.find params[:id]
    render :layout => "popup"
  end

  def import_personal_doc    
    @interview = Interview.find(params[:id])
    @attachment = @interview.attachments.new(params[:attachment])
    @attachment.save
  end
  
  def download_attachment
    @attachment = Attachment.find(params[:attachment_id])
    send_file @attachment.data.path
  end

  def search    
    @search = Interview.search(params[:search])
    @interviews = @search.all.paginate(:per_page=>9,:page=>params[:page])
    respond_to do |format|
      format.csv do
        generate_csv_headers("Interview-#{Time.now.strftime("%Y%m%d")}")
        render :action=>:index
      end
      format.html { render :action=>:index }
    end
  end 

  def generate_csv_headers(filename)
    headers.merge!({
        'Cache-Control'             => 'must-revalidate, post-check=0, pre-check=0',
        'Content-Type'              => 'csv',
        'Content-Disposition'       => "attachment; filename=\"#{filename}\"",
        'Content-Transfer-Encoding' => 'binary'
      })
  end

  def get_content_to_display
    respond_to do |format|
      render :update do |page|
        page.replace_html "mainBox", :partial => 'page1'
      end
    end
  end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<div class="mainbox">
  <div style="margin-left: 200px;">
    <%= form_for(@interview) do |f| %>
      <% if @interview.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>
          <ul>
            <% @interview.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <table id="form1">
        <tr>
      <div class="field">
              <th><%= f.label :Name %><br /></th><td>
        <%= f.text_field :name %></td>
      </div></tr><tr>
      <div class="field">
        <th>E-<%= f.label :Mail %><br /></th><td>
        <%= f.text_field :email %></td>
      </div></tr><tr>
      <div class="field">
        <th>Total<%= f.label :Experience %><br /></th><td>
        <%= f.text_field :total_exp %></td>
      </div></tr><tr>
      <div class="field">
        <th><%= f.label :Skills %><br /></th><td>
        <%= f.text_field :ror_exp %></td>
      </div></tr><tr>
      <div class="field">
        <th>Date Of <%= f.label :Interview %><br /></th><td>
        <%= f.text_field :doi %></td>
      </div></tr><tr>
      <div class="field">
        <th>Type or <%= f.label :Location %><br /></th><td>
        <%= f.text_field :type_location %></td>
      </div></tr><tr>
      <div class="field">
        <th><%= f.label :Status %><br /></th><td>
        <%= f.text_field :result %></td>
      </div></tr><tr>
      <div class="field">
        <th>Contact <%= f.label :Number %><br /></th><td>
        <%= f.text_field :phoneNumber %></td>
      </div></tr><tr>
      <div class="field">
        <th><%= f.label :Remarks %><br /></th><td>
        <%= f.text_area :remarks %></td>
      </div></tr><tr></table>
      <div class="actions">
        <center><tr><%= f.submit %></tr>
      </div></tr>
    <% end %>
      
  </div>
</div>

app/views/interviews/edit.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
<h1>Editing interview</h1>
<center>
<%= render 'form' %>

</div>

app/views/interviews/index.csv.erb
<%- headers = ["Id", "Name","Phone Number","Email","Total Experience","ROR Experience", "DOI","Location","Result"] -%>
<%= FasterCSV.generate_line headers %>
<%- @interviews.each do |n| -%>
<%- row = [ n.id,n.name,n.phoneNumber,n.email,n.total_exp,n.ror_exp,n.doi,n.type_location,n.result ] -%>
<%=  FasterCSV.generate_line row %>
<%- end -%>

app/views/interviews/index.html.erb
<%=render :partial=>"search"%>

        <div class="column contactlist">
          <div class="mainbox">
              <div class="menu">
                 <div id="tabs" class="noprint">
                   <div>
           <ul class="box" id="mainMenu">
             <li><%=link_to "Export Search Results", request.parameters.merge({:format => :csv}),{:class=>"export"}%></li>
             <li><%=link_to "Add New Candidates", new_interview_path%></li>
               </ul> </div></div>
              </div>
              <div class="displaying">
                       <%= page_entries_info @interviews %>
              </div>
                    <%if @interviews.blank?%>
            <h3>  No Results Found</h3>
  <%end%>

        <table class="standard_table" cellpadding="0" cellspacing="0" >
                <tbody><tr class="list">

                   <th>Name</th>
                    <th>Document List</th>
                   <th>Document Import</th>
                </tr>

                <% @interviews.each_with_index do |interview,i| %>
  <tr class="<%=cycle('', 'alt_row')%>">

    <td>
      <%= link_to "#{h interview.name.upcase}",interview %>
      <td><%interview.attachments.each_with_index do |attachment,i|%>
        <%= link_to "#{attachment.data_file_name}", download_attachment_url(:id=>interview.id,:attachment_id=>attachment.id) %>
        <%= "," if i+1 < interview.attachments.length%>
    <%end%>
    </td>
        <td><%=  link_to image_tag("paperclip_icon.png", :alt => "Upload File", :title => "UPLOAD",:width => 20, :height => 20), "javascript:void(0);",:onclick=>"window.open('#{upload_personal_doc_url(:id=>interview.id)}','Import Document','Height=200px;width=960px;')" %>
        <%=  link_to image_tag("Symbols Delete.png", :alt => "Delete", :title => "DELETE",:remote=>true,:width => 20, :height => 25), interview, :confirm => 'Are you sure?', :method => :delete %></td>
       	
        </td>
  </tr>
<% end %>

              </tbody>
        </table>
            <%=will_paginate @interviews%>
            <div class="clear"></div>

          </div></div>

app/views/interviews/new.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
<h1>New interview</h1>

<%= render 'form' %>

<%= link_to 'Back', interviews_path %>
</div>

app/views/interviews/show.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
  <div class="mainbox">
    <p id="notice"><%= notice %></td></tr>

    <table id="form2" style="margin-left: 200px;">
      <caption><center><b>Details of <%= @interview.name.upcase %> </b></center></caption>
      <th>Experience:</th><td>
        <%= @interview.total_exp %>
      </td></tr>
      <tr>
        <th>Skills:</th><td>
          <%= @interview.ror_exp %>
        </td></tr>
      <tr>
        <th>Date Of Interview:</th><td>
          <%= @interview.doi %>
        </td></tr>
      <tr>
        <th>Type orLocation:</th><td>
          <%= @interview.type_location %>
        </td></tr>
      <tr>
        <th>Status:</th><td>
          <%= @interview.result %>
        </td></tr>
      <tr>
        <th>Contact Number:</th><td>
          <%= @interview.phoneNumber %>
        </td></tr>
      <tr>
        <th>Remarks:</th><td>
          <%= @interview.remarks %>
        </td></tr>
      <tr>
        <th>Email:</th><td>
          <%= @interview.email %>
        </td></tr>
      <tr>
        <td><center><%= link_to 'Edit', edit_interview_path(@interview) %></td>
        <td><center><%= link_to 'Back', interviews_path %></td>
      </tr>
    </table>
  </div>
</div>